# Generated by Django 3.0.7 on 2020-06-18 16:44

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcard',
            name='initialised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='GBP', max_digits=14),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
    ]
